apiVersion: v1
kind: Service
metadata:
  name: aml-dashboard
  labels:
    app: aml-dashboard
spec:
  type: ClusterIP
  selector:
    app: aml-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
